### ISSUE TITLE
phpunit

### ISSUE THREAD

**Issue by fietronic** [mre/Process#1]
what is phpunit used for in this? Not sure which lines it's used on.

**Comment by mre** [comment]
Hi.
Do you mean this? 
https://github.com/mre/Process/blob/master/test/mre/ProcessTest.php

**Comment by fietronic** [comment]
Oh, yeah that. 

So is it possible to use the main class standalone, without composer/phpunit?

I'm not exactly sure what autoload.php does. Can I just include files manually?

**Comment by mre** [comment]
You could, but I'd suggest to use it together with an autoloader. 
For example, you can use [composer](https://getcomposer.org) for package management.
Here is the documenation: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

Sorry for the late reply.
